name: go_food_br
description: Gofood delivery.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  group_list_view: ^1.0.5
  location: ^3.0.2
  flutter_masked_text: ^0.8.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bloc_pattern: ^2.5.1
  google_fonts: ^0.3.10
  flutter_screenutil: ^1.1.0
  google_sign_in: ^4.4.0
  firebase_auth: ^0.15.5+3
  dio: ^3.0.9
  connectivity: ^0.4.3+2
  rxdart: ^0.23.1
  intl: ^0.16.1
  rounded_modal: ^1.0.1
  share: ^0.6.4
  url_launcher: ^5.4.7
  flutter_rating_bar: ^3.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/



flutter_native_splash:
  color: "850284"
  android_disable_fullscreen: true